version: "3"

services:
  postgres:
    container_name: db
    environment:
      POSTGRES_PASSWORD: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      - "discovery.type=single-node"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  mailpit:
    container_name: mailpit
    image: axllent/mailpit
    ports:
      - 8025:8025
      - 1025:1025

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - elasticsearch
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file: .env
    environment:
      RAILS_ENV: development
      ELASTICSEARCH_URL: http://elasticsearch:9200
    restart: always
    entrypoint: ./entrypoints/docker-entrypoint.sh
    links:
      - mailpit

volumes:
  postgres-data:
  elasticsearch-data:
  app:
